name: "Crypto Service Suite CI"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 18.x]
    steps:
      - run: echo ${{github.ref}}
      - uses: actions/checkout@v2
      - name: Build on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install, build, and test
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run build
          pnpm run test

      - name: Testing & Coverage
        run: |
          npm run test

      - name: Coveralls Crypto-Cli
        uses: coverallsapp/github-action@master
        with:
          base-path: packages/crypto-cli
          flag-name: crypto-cli
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          path-to-lcov: ./packages/crypto-cli/coverage/lcov.info

      - name: Coveralls Crypto-Lib
        uses: coverallsapp/github-action@master
        with:
          base-path: packages/crypto-lib
          flag-name: crypto-lib
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          path-to-lcov: ./packages/crypto-lib/coverage/lcov.info
