name: "Crypto Service CI"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Installing deps
        run: npm install

      - name: Building
        run: npm run build

      - name: Testing & Coverage
        run: |
          npm run test

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
