name: "Crypto Service CI"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install yarn dependencies
        # run: yarn --frozen-lockfile --ignore-scripts
        run: |
          yarn run bootstrap

      - name: Run lint fix
        run: |
          yarn lint:fix

      - name: Run prettier
        run: |
          yarn format

      - name: Run remark
        run: |
          yarn markdown

      - name: Building
        run: |
          yarn run build

      - name: Testing & Coverage
        run: |
          yarn run test

      - name: Coveralls Crypto-Cli
        uses: coverallsapp/github-action@master
        with:
          base-path: packages/crypto-cli
          flag-name: crypto-cli
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          path-to-lcov: ./packages/crypto-cli/coverage/lcov.info

      - name: Coveralls Crypto-Lib
        uses: coverallsapp/github-action@master
        with:
          base-path: packages/crypto-lib
          flag-name: crypto-lib
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          path-to-lcov: ./packages/crypto-lib/coverage/lcov.info
